"""add_google_place_and_request_locations

Revision ID: 49aa32de98bf
Revises: 7411d6f5e980
Create Date: 2026-09-29 21:33:44.584844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49aa32de98bf'
down_revision: Union[str, Sequence[str], None] = '7411d6f5e980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=50), nullable=False),
    sa.Column('location_precision', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_locations_area'), 'request_locations', ['area'], unique=False)
    op.create_index(op.f('ix_request_locations_city'), 'request_locations', ['city'], unique=False)
    op.create_index(op.f('ix_request_locations_google_place_id'), 'request_locations', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_request_locations_id'), 'request_locations', ['id'], unique=False)
    op.create_index(op.f('ix_request_locations_request_id'), 'request_locations', ['request_id'], unique=True)
    op.create_index(op.f('ix_request_locations_state'), 'request_locations', ['state'], unique=False)
    op.add_column('locations', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('formatted_address', sa.String(length=500), nullable=True))
    op.add_column('locations', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('locations', sa.Column('location_source', sa.String(length=50), server_default='manual', nullable=False))
    op.add_column('locations', sa.Column('location_precision', sa.String(length=50), server_default='locality', nullable=False))
    op.create_index(op.f('ix_locations_google_place_id'), 'locations', ['google_place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_google_place_id'), table_name='locations')
    op.drop_column('locations', 'location_precision')
    op.drop_column('locations', 'location_source')
    op.drop_column('locations', 'postal_code')
    op.drop_column('locations', 'formatted_address')
    op.drop_column('locations', 'google_place_id')
    op.drop_index(op.f('ix_request_locations_state'), table_name='request_locations')
    op.drop_index(op.f('ix_request_locations_request_id'), table_name='request_locations')
    op.drop_index(op.f('ix_request_locations_id'), table_name='request_locations')
    op.drop_index(op.f('ix_request_locations_google_place_id'), table_name='request_locations')
    op.drop_index(op.f('ix_request_locations_city'), table_name='request_locations')
    op.drop_index(op.f('ix_request_locations_area'), table_name='request_locations')
    op.drop_table('request_locations')
    # ### end Alembic commands ###
